default: &default
  todo_notifications_worker:
    cron: "*/10 * * * *"
    class: "Articles::FutureArticleUpdatesWorker"
    queue: "default"

development:
  todo_notifications_worker:
    cron: "* * * * *"
    class: "Articles::FutureArticleUpdatesWorker"
    queue: "default"

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
